alias ..='cd ..';
alias ...='cd ../..';
alias wtf='exit';
alias top='htop';
alias his='history | grep ';
alias gcs='git commit -S -m';
alias gch='git commit -S -m `hostname`';
alias gfm='git fetch && git merge origin/master';
alias pks='tail -f /var/lib/sks/db.log /var/lib/sks/recon.log';
